
<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>pyaedt.modeler.Circuit &#8212; PyAEDT</title>
    
<script>
  document.documentElement.dataset.mode = localStorage.getItem("mode") || "";
  document.documentElement.dataset.theme = localStorage.getItem("theme") || "light"
</script>

  <!-- Loaded before other Sphinx assets -->
  <link href="../../../_static/styles/theme.css?digest=92025949c220c2e29695" rel="stylesheet">
<link href="../../../_static/styles/pydata-sphinx-theme.css?digest=92025949c220c2e29695" rel="stylesheet">


  <link rel="stylesheet"
    href="../../../_static/vendor/fontawesome/5.13.0/css/all.min.css">
  <link rel="preload" as="font" type="font/woff2" crossorigin
    href="../../../_static/vendor/fontawesome/5.13.0/webfonts/fa-solid-900.woff2">
  <link rel="preload" as="font" type="font/woff2" crossorigin
    href="../../../_static/vendor/fontawesome/5.13.0/webfonts/fa-brands-400.woff2">

    <link rel="stylesheet" type="text/css" href="../../../_static/pygments.css" />
    <link rel="stylesheet" type="text/css" href="../../../_static/copybutton.css" />
    <link rel="stylesheet" type="text/css" href="../../../_static/graphviz.css" />
    <link rel="stylesheet" type="text/css" href="../../../_static/css\ansys_sphinx_theme.css" />
    <link rel="stylesheet" type="text/css" href="../../../_static/sg_gallery.css" />
    <link rel="stylesheet" type="text/css" href="../../../_static/sg_gallery-binder.css" />
    <link rel="stylesheet" type="text/css" href="../../../_static/sg_gallery-dataframe.css" />
    <link rel="stylesheet" type="text/css" href="../../../_static/sg_gallery-rendered-html.css" />

  <!-- Pre-loaded scripts that we'll load fully later -->
  <link rel="preload" as="script" href="../../../_static/scripts/pydata-sphinx-theme.js?digest=92025949c220c2e29695">

    
        <link href="../../../_static/css/breadcrumbs.css" rel="stylesheet">
    
    <script data-url_root="../../../" id="documentation_options" src="../../../_static/documentation_options.js"></script>
    <script src="../../../_static/jquery.js"></script>
    <script src="../../../_static/underscore.js"></script>
    <script src="../../../_static/_sphinx_javascript_frameworks_compat.js"></script>
    <script src="../../../_static/doctools.js"></script>
    <script src="../../../_static/sphinx_highlight.js"></script>
    <script src="../../../_static/clipboard.min.js"></script>
    <script src="../../../_static/copybutton.js"></script>
    <link rel="shortcut icon" href="../../../_static/ansys-favicon.png"/>
    <link rel="index" title="Index" href="../../../genindex.html" />
    <link rel="search" title="Search" href="../../../search.html" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="docsearch:language" content="en">
  </head>
  
  
  <body data-spy="scroll" data-target="#bd-toc-nav" data-offset="180" data-default-mode="">
    <div class="bd-header-announcement container-fluid" id="banner">
      

    </div>

    
    
    <nav class="bd-header navbar navbar-light navbar-expand-lg bg-light fixed-top bd-navbar" id="navbar-main"><div class="bd-header__inner container-xl">

  <div id="navbar-start">
    
    
  


<a class="navbar-brand logo" href="../../../index.html">
  
  
  
  
    <img src="../../../_static/pyansys-logo-black-cropped.png" class="logo__image only-light" alt="Logo image">
    <img src="../../../_static/pyansys-logo-black-cropped.png" class="logo__image only-dark" alt="Logo image">
  
  
</a>
    
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapsible" aria-controls="navbar-collapsible" aria-expanded="false" aria-label="Toggle navigation">
    <span class="fas fa-bars"></span>
  </button>

  
  <div id="navbar-collapsible" class="col-lg-9 collapse navbar-collapse">
    <div id="navbar-center" class="mr-auto">
      
      <div class="navbar-center-item">
        <ul id="navbar-main-elements" class="navbar-nav">
    <li class="toctree-l1 nav-item">
 <a class="reference internal nav-link" href="../../../Getting_started/index.html">
  Getting started
 </a>
</li>

<li class="toctree-l1 nav-item">
 <a class="reference internal nav-link" href="../../../User_guide/index.html">
  User guide
 </a>
</li>

<li class="toctree-l1 nav-item">
 <a class="reference internal nav-link" href="../../../API/index.html">
  API reference
 </a>
</li>

<li class="toctree-l1 nav-item">
 <a class="reference internal nav-link" href="../../../examples/index.html">
  Examples
 </a>
</li>

<li class="toctree-l1 nav-item">
 <a class="reference internal nav-link" href="../../../Contributing.html">
  Contribute
 </a>
</li>

    
</ul>
      </div>
      
    </div>

    <div id="navbar-end">
      
      <div class="navbar-end-item">
        <span id="theme-switch" class="btn btn-sm btn-outline-primary navbar-btn rounded-circle">
    <a class="theme-switch" data-mode="light"><i class="fas fa-sun"></i></a>
    <a class="theme-switch" data-mode="dark"><i class="far fa-moon"></i></a>
    <a class="theme-switch" data-mode="auto"><i class="fas fa-adjust"></i></a>
</span>
      </div>
      
      <div class="navbar-end-item">
        <ul id="navbar-icon-links" class="navbar-nav" aria-label="Icon Links">
        <li class="nav-item">
          <a class="nav-link" href="https://github.com/pyansys/pyaedt" rel="noopener" target="_blank" title="GitHub"><span><i class="fab fa-github-square"></i></span>
            <label class="sr-only">GitHub</label></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="https://github.com/pyansys/pyaedt/discussions" rel="noopener" target="_blank" title="Support"><span><i class="fa fa-comment fa-fw"></i></span>
            <label class="sr-only">Support</label></a>
        </li>
      </ul>
      </div>
      
    </div>
  </div>
</div>
    </nav>
    
    
    
        <div class="container-xl">
    <div class="row">
        <div class="col-12 col-md-3" id="breadcrumbs-spacer"></div>
        <div class="col-12 col-md-11 col-xl-9" id="breadcrumbs">
          
    <div class="related" role="navigation" aria-label="related navigation">
      <h3>Navigation</h3>
      <ul>
    
        <li class="nav-item nav-item-additional-breadcrumb"><a href="https://docs.pyansys.com/">PyAnsys</a> » </li>
    
    
        <li class="nav-item nav-item-0"><a href="../../../index.html">PyAEDT</a> » </li>
    

          <li class="nav-item nav-item-1"><a href="../../index.html" accesskey="U">Module code</a> » </li>
        <li class="nav-item nav-item-this"><a href="">pyaedt.modeler.Circuit</a></li> 
      </ul>
    </div>
        </div>
  </div>
</div>
    


    <div class="bd-container container-xl">
      <div class="bd-container__inner row">
          

<!-- Only show if we have sidebars configured, else just a small margin  -->
<div class="bd-sidebar-primary col-12 col-md-3 bd-sidebar">
  <div class="sidebar-start-items"><form class="bd-search d-flex align-items-center" action="../../../search.html" method="get">
  <i class="icon fas fa-search"></i>
  <input type="search" class="form-control" name="q" id="search-input" placeholder="Search the docs ..." aria-label="Search the docs ..." autocomplete="off" >
</form><nav class="bd-links" id="bd-docs-nav" aria-label="Main navigation">
  <div class="bd-toc-item active">
    
    
    
  </div>
</nav>
  </div>
  <div class="sidebar-end-items">
  </div>
</div>


          


<div class="bd-sidebar-secondary d-none d-xl-block col-xl-2 bd-toc">
  
</div>


          
          
          <div class="bd-content col-12 col-md-9 col-xl-7">
              
              <article class="bd-article" role="main">
                
  <h1>Source code for pyaedt.modeler.Circuit</h1><div class="highlight"><pre>
<span></span><span class="c1"># -*- coding: utf-8 -*-</span>
<span class="kn">from</span> <span class="nn">pyaedt.generic.constants</span> <span class="kn">import</span> <span class="n">AEDT_UNITS</span>
<span class="kn">from</span> <span class="nn">pyaedt.generic.general_methods</span> <span class="kn">import</span> <span class="n">_retry_ntimes</span>
<span class="kn">from</span> <span class="nn">pyaedt.generic.general_methods</span> <span class="kn">import</span> <span class="n">pyaedt_function_handler</span>
<span class="kn">from</span> <span class="nn">pyaedt.modeler.Modeler</span> <span class="kn">import</span> <span class="n">Modeler</span>
<span class="kn">from</span> <span class="nn">pyaedt.modeler.Object3d</span> <span class="kn">import</span> <span class="n">CircuitComponent</span>
<span class="kn">from</span> <span class="nn">pyaedt.modeler.Primitives3DLayout</span> <span class="kn">import</span> <span class="n">Primitives3DLayout</span>
<span class="kn">from</span> <span class="nn">pyaedt.modeler.PrimitivesEmit</span> <span class="kn">import</span> <span class="n">EmitComponent</span>
<span class="kn">from</span> <span class="nn">pyaedt.modeler.PrimitivesEmit</span> <span class="kn">import</span> <span class="n">EmitComponents</span>
<span class="kn">from</span> <span class="nn">pyaedt.modeler.PrimitivesMaxwellCircuit</span> <span class="kn">import</span> <span class="n">MaxwellCircuitComponents</span>
<span class="kn">from</span> <span class="nn">pyaedt.modeler.PrimitivesNexxim</span> <span class="kn">import</span> <span class="n">NexximComponents</span>
<span class="kn">from</span> <span class="nn">pyaedt.modeler.PrimitivesTwinBuilder</span> <span class="kn">import</span> <span class="n">TwinBuilderComponents</span>
<span class="kn">from</span> <span class="nn">pyaedt.modules.LayerStackup</span> <span class="kn">import</span> <span class="n">Layers</span>


<span class="k">class</span> <span class="nc">ModelerCircuit</span><span class="p">(</span><span class="n">Modeler</span><span class="p">):</span>
    <span class="sd">&quot;&quot;&quot;ModelerCircuit class.</span>

<span class="sd">    Parameters</span>
<span class="sd">    ----------</span>
<span class="sd">    app : :class:`pyaedt.application.AnalysisNexxim.FieldAnalysisCircuit`</span>

<span class="sd">    Examples</span>
<span class="sd">    --------</span>
<span class="sd">    &gt;&gt;&gt; from pyaedt import Circuit</span>
<span class="sd">    &gt;&gt;&gt; app = Circuit()</span>
<span class="sd">    &gt;&gt;&gt; my_modeler = app.modeler</span>
<span class="sd">    &quot;&quot;&quot;</span>

    <span class="k">def</span> <span class="fm">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">app</span><span class="p">):</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">_app</span> <span class="o">=</span> <span class="n">app</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">o_def_manager</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">_app</span><span class="o">.</span><span class="n">odefinition_manager</span>
        <span class="n">Modeler</span><span class="o">.</span><span class="fm">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">app</span><span class="p">)</span>

    <span class="nd">@property</span>
    <span class="k">def</span> <span class="nf">o_component_manager</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="sd">&quot;&quot;&quot;Component manager object.&quot;&quot;&quot;</span>
        <span class="k">return</span> <span class="bp">self</span><span class="o">.</span><span class="n">_app</span><span class="o">.</span><span class="n">o_component_manager</span>

    <span class="nd">@property</span>
    <span class="k">def</span> <span class="nf">o_model_manager</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="sd">&quot;&quot;&quot;Model manager object.&quot;&quot;&quot;</span>
        <span class="k">return</span> <span class="bp">self</span><span class="o">.</span><span class="n">_app</span><span class="o">.</span><span class="n">o_model_manager</span>

    <span class="nd">@property</span>
    <span class="k">def</span> <span class="nf">oeditor</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="sd">&quot;&quot;&quot;Oeditor Module.</span>

<span class="sd">        References</span>
<span class="sd">        ----------</span>

<span class="sd">        &gt;&gt;&gt; oEditor = oDesign.SetActiveEditor(&quot;SchematicEditor&quot;)&quot;&quot;&quot;</span>
        <span class="k">return</span> <span class="bp">self</span><span class="o">.</span><span class="n">_app</span><span class="o">.</span><span class="n">oeditor</span>

    <span class="nd">@property</span>
    <span class="k">def</span> <span class="nf">obounding_box</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="sd">&quot;&quot;&quot;Bounding box.</span>

<span class="sd">        References</span>
<span class="sd">        ----------</span>

<span class="sd">        &gt;&gt;&gt; oEditor.GetModelBoundingBox()&quot;&quot;&quot;</span>
        <span class="k">return</span> <span class="bp">self</span><span class="o">.</span><span class="n">oeditor</span><span class="o">.</span><span class="n">GetModelBoundingBox</span><span class="p">()</span>

    <span class="nd">@pyaedt_function_handler</span><span class="p">()</span>
    <span class="k">def</span> <span class="nf">zoom_to_fit</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="sd">&quot;&quot;&quot;Zoom To Fit.</span>

<span class="sd">        References</span>
<span class="sd">        ----------</span>

<span class="sd">        &gt;&gt;&gt; oEditor.ZoomToFit</span>
<span class="sd">        &quot;&quot;&quot;</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">oeditor</span><span class="o">.</span><span class="n">ZoomToFit</span><span class="p">()</span>

    <span class="nd">@pyaedt_function_handler</span><span class="p">()</span>
    <span class="k">def</span> <span class="nf">connect_schematic_components</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">firstcomponent</span><span class="p">,</span> <span class="n">secondcomponent</span><span class="p">,</span> <span class="n">pinnum_first</span><span class="o">=</span><span class="mi">2</span><span class="p">,</span> <span class="n">pinnum_second</span><span class="o">=</span><span class="mi">1</span><span class="p">):</span>
        <span class="sd">&quot;&quot;&quot;Connect schematic components.</span>

<span class="sd">        Parameters</span>
<span class="sd">        ----------</span>
<span class="sd">        firstcomponent : str</span>
<span class="sd">           Starting (right) component.</span>
<span class="sd">        secondcomponent : str</span>
<span class="sd">           Ending (left) component for the connection line.</span>
<span class="sd">        pinnum_first : str, optional</span>
<span class="sd">             Number of the pin at which to terminate the connection from the right end of the</span>
<span class="sd">             starting component. The default is ``2``.</span>
<span class="sd">        pinnum_second : str, optional</span>
<span class="sd">             Number of the pin at which to termiante the connection from the left end of the</span>
<span class="sd">             ending component. The default is ``1``.</span>

<span class="sd">        Returns</span>
<span class="sd">        -------</span>
<span class="sd">        bool</span>
<span class="sd">            ``True`` when successful, ``False`` when failed.</span>

<span class="sd">        References</span>
<span class="sd">        ----------</span>

<span class="sd">        &gt;&gt;&gt; oEditor.CreateWire</span>
<span class="sd">        &quot;&quot;&quot;</span>
        <span class="n">obj1</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">components</span><span class="p">[</span><span class="n">firstcomponent</span><span class="p">]</span>
        <span class="k">if</span> <span class="s2">&quot;Port&quot;</span> <span class="ow">in</span> <span class="n">obj1</span><span class="o">.</span><span class="n">composed_name</span><span class="p">:</span>
            <span class="n">pos1</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">oeditor</span><span class="o">.</span><span class="n">GetPropertyValue</span><span class="p">(</span><span class="s2">&quot;BaseElementTab&quot;</span><span class="p">,</span> <span class="n">obj1</span><span class="o">.</span><span class="n">composed_name</span><span class="p">,</span> <span class="s2">&quot;Component Location&quot;</span><span class="p">)</span><span class="o">.</span><span class="n">split</span><span class="p">(</span><span class="s2">&quot;, &quot;</span><span class="p">)</span>
            <span class="n">pos1</span> <span class="o">=</span> <span class="p">[</span><span class="nb">float</span><span class="p">(</span><span class="n">i</span><span class="o">.</span><span class="n">strip</span><span class="p">()[:</span><span class="o">-</span><span class="mi">3</span><span class="p">])</span> <span class="o">*</span> <span class="mf">0.0000254</span> <span class="k">for</span> <span class="n">i</span> <span class="ow">in</span> <span class="n">pos1</span><span class="p">]</span>
            <span class="k">if</span> <span class="s2">&quot;GPort&quot;</span> <span class="ow">in</span> <span class="n">obj1</span><span class="o">.</span><span class="n">composed_name</span><span class="p">:</span>
                <span class="n">pos1</span><span class="p">[</span><span class="mi">1</span><span class="p">]</span> <span class="o">+=</span> <span class="mf">0.00254</span>
        <span class="k">else</span><span class="p">:</span>
            <span class="n">pins1</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">components</span><span class="o">.</span><span class="n">get_pins</span><span class="p">(</span><span class="n">firstcomponent</span><span class="p">)</span>
            <span class="n">pos1</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">components</span><span class="o">.</span><span class="n">get_pin_location</span><span class="p">(</span><span class="n">firstcomponent</span><span class="p">,</span> <span class="n">pins1</span><span class="p">[</span><span class="n">pinnum_first</span> <span class="o">-</span> <span class="mi">1</span><span class="p">])</span>
        <span class="n">obj2</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">components</span><span class="p">[</span><span class="n">secondcomponent</span><span class="p">]</span>
        <span class="k">if</span> <span class="s2">&quot;Port&quot;</span> <span class="ow">in</span> <span class="n">obj2</span><span class="o">.</span><span class="n">composed_name</span><span class="p">:</span>
            <span class="n">pos2</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">oeditor</span><span class="o">.</span><span class="n">GetPropertyValue</span><span class="p">(</span><span class="s2">&quot;BaseElementTab&quot;</span><span class="p">,</span> <span class="n">obj2</span><span class="o">.</span><span class="n">composed_name</span><span class="p">,</span> <span class="s2">&quot;Component Location&quot;</span><span class="p">)</span><span class="o">.</span><span class="n">split</span><span class="p">(</span><span class="s2">&quot;, &quot;</span><span class="p">)</span>
            <span class="n">pos2</span> <span class="o">=</span> <span class="p">[</span><span class="nb">float</span><span class="p">(</span><span class="n">i</span><span class="o">.</span><span class="n">strip</span><span class="p">()[:</span><span class="o">-</span><span class="mi">3</span><span class="p">])</span> <span class="o">*</span> <span class="mf">0.0000254</span> <span class="k">for</span> <span class="n">i</span> <span class="ow">in</span> <span class="n">pos2</span><span class="p">]</span>
            <span class="k">if</span> <span class="s2">&quot;GPort&quot;</span> <span class="ow">in</span> <span class="n">obj2</span><span class="o">.</span><span class="n">composed_name</span><span class="p">:</span>
                <span class="n">pos2</span><span class="p">[</span><span class="mi">1</span><span class="p">]</span> <span class="o">+=</span> <span class="mf">0.00254</span>

        <span class="k">else</span><span class="p">:</span>
            <span class="n">pins2</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">components</span><span class="o">.</span><span class="n">get_pins</span><span class="p">(</span><span class="n">secondcomponent</span><span class="p">)</span>
            <span class="n">pos2</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">components</span><span class="o">.</span><span class="n">get_pin_location</span><span class="p">(</span><span class="n">secondcomponent</span><span class="p">,</span> <span class="n">pins2</span><span class="p">[</span><span class="n">pinnum_second</span> <span class="o">-</span> <span class="mi">1</span><span class="p">])</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">components</span><span class="o">.</span><span class="n">create_wire</span><span class="p">([</span><span class="n">pos1</span><span class="p">,</span> <span class="n">pos2</span><span class="p">])</span>
        <span class="k">return</span> <span class="kc">True</span>

    <span class="nd">@pyaedt_function_handler</span><span class="p">()</span>
    <span class="k">def</span> <span class="nf">_get_components_selections</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">selections</span><span class="p">,</span> <span class="n">return_as_list</span><span class="o">=</span><span class="kc">True</span><span class="p">):</span>
        <span class="n">sels</span> <span class="o">=</span> <span class="p">[]</span>
        <span class="k">if</span> <span class="ow">not</span> <span class="nb">isinstance</span><span class="p">(</span><span class="n">selections</span><span class="p">,</span> <span class="nb">list</span><span class="p">):</span>
            <span class="n">selections</span> <span class="o">=</span> <span class="p">[</span><span class="n">selections</span><span class="p">]</span>
        <span class="k">for</span> <span class="n">sel</span> <span class="ow">in</span> <span class="n">selections</span><span class="p">:</span>
            <span class="k">if</span> <span class="nb">isinstance</span><span class="p">(</span><span class="n">sel</span><span class="p">,</span> <span class="nb">int</span><span class="p">):</span>
                <span class="n">sels</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="bp">self</span><span class="o">.</span><span class="n">schematic</span><span class="o">.</span><span class="n">components</span><span class="p">[</span><span class="n">sel</span><span class="p">]</span><span class="o">.</span><span class="n">composed_name</span><span class="p">)</span>
            <span class="k">elif</span> <span class="nb">isinstance</span><span class="p">(</span><span class="n">sel</span><span class="p">,</span> <span class="p">(</span><span class="n">CircuitComponent</span><span class="p">,</span> <span class="n">EmitComponent</span><span class="p">)):</span>
                <span class="n">sels</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="n">sel</span><span class="o">.</span><span class="n">composed_name</span><span class="p">)</span>
            <span class="k">else</span><span class="p">:</span>
                <span class="k">for</span> <span class="n">el</span> <span class="ow">in</span> <span class="nb">list</span><span class="p">(</span><span class="bp">self</span><span class="o">.</span><span class="n">schematic</span><span class="o">.</span><span class="n">components</span><span class="o">.</span><span class="n">values</span><span class="p">()):</span>
                    <span class="k">if</span> <span class="n">sel</span> <span class="ow">in</span> <span class="p">[</span><span class="n">el</span><span class="o">.</span><span class="n">InstanceName</span><span class="p">,</span> <span class="n">el</span><span class="o">.</span><span class="n">composed_name</span><span class="p">,</span> <span class="n">el</span><span class="o">.</span><span class="n">name</span><span class="p">]:</span>
                        <span class="n">sels</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="n">el</span><span class="o">.</span><span class="n">composed_name</span><span class="p">)</span>
        <span class="k">if</span> <span class="ow">not</span> <span class="n">return_as_list</span><span class="p">:</span>
            <span class="k">return</span> <span class="s2">&quot;, &quot;</span><span class="o">.</span><span class="n">join</span><span class="p">(</span><span class="n">sels</span><span class="p">)</span>
        <span class="k">return</span> <span class="n">sels</span>


<div class="viewcode-block" id="ModelerNexxim"><a class="viewcode-back" href="../../../API/_autosummary/pyaedt.modeler.Circuit.ModelerNexxim.html#pyaedt.modeler.Circuit.ModelerNexxim">[docs]</a><span class="k">class</span> <span class="nc">ModelerNexxim</span><span class="p">(</span><span class="n">ModelerCircuit</span><span class="p">):</span>
    <span class="sd">&quot;&quot;&quot;ModelerNexxim class.</span>

<span class="sd">    Parameters</span>
<span class="sd">    ----------</span>
<span class="sd">    app : :class:`pyaedt.application.AnalysisNexxim.FieldAnalysisCircuit`</span>

<span class="sd">    &quot;&quot;&quot;</span>

    <span class="k">def</span> <span class="fm">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">app</span><span class="p">):</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">_app</span> <span class="o">=</span> <span class="n">app</span>
        <span class="n">ModelerCircuit</span><span class="o">.</span><span class="fm">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">app</span><span class="p">)</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">_schematic</span> <span class="o">=</span> <span class="n">NexximComponents</span><span class="p">(</span><span class="bp">self</span><span class="p">)</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">_layouteditor</span> <span class="o">=</span> <span class="kc">None</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">layers</span> <span class="o">=</span> <span class="n">Layers</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">roughnessunits</span><span class="o">=</span><span class="s2">&quot;um&quot;</span><span class="p">)</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">_primitives</span> <span class="o">=</span> <span class="n">Primitives3DLayout</span><span class="p">(</span><span class="n">app</span><span class="p">)</span>

    <span class="nd">@property</span>
    <span class="k">def</span> <span class="nf">layouteditor</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="sd">&quot;&quot;&quot;Return the Circuit Layout Editor.</span>

<span class="sd">        References</span>
<span class="sd">        ----------</span>

<span class="sd">        &gt;&gt;&gt; oDesign.SetActiveEditor(&quot;Layout&quot;)</span>
<span class="sd">        &quot;&quot;&quot;</span>
        <span class="k">return</span> <span class="bp">self</span><span class="o">.</span><span class="n">_app</span><span class="o">.</span><span class="n">layouteditor</span>

    <span class="nd">@property</span>
    <span class="k">def</span> <span class="nf">schematic</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="sd">&quot;&quot;&quot;Schematic Component.</span>

<span class="sd">        Returns</span>
<span class="sd">        -------</span>
<span class="sd">        :class:`pyaedt.modeler.PrimitivesNexxim.NexximComponents`</span>
<span class="sd">        &quot;&quot;&quot;</span>
        <span class="k">return</span> <span class="bp">self</span><span class="o">.</span><span class="n">_schematic</span>

    <span class="nd">@property</span>
    <span class="k">def</span> <span class="nf">components</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="sd">&quot;&quot;&quot;Schematic Component.</span>

<span class="sd">        .. deprecated:: 0.4.13</span>
<span class="sd">           Use :func:`Circuit.modeler.schematic` instead.</span>

<span class="sd">        Returns</span>
<span class="sd">        -------</span>
<span class="sd">        :class:`pyaedt.modeler.PrimitivesNexxim.NexximComponents`</span>
<span class="sd">        &quot;&quot;&quot;</span>
        <span class="k">return</span> <span class="bp">self</span><span class="o">.</span><span class="n">_schematic</span>

    <span class="nd">@property</span>
    <span class="k">def</span> <span class="nf">edb</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="sd">&quot;&quot;&quot;EDB.</span>

<span class="sd">        Returns</span>
<span class="sd">        -------</span>
<span class="sd">        :class:`pyaedt.Edb`</span>
<span class="sd">            edb_core object if it exists.</span>

<span class="sd">        &quot;&quot;&quot;</span>
        <span class="c1"># TODO Check why it crashes when multiple circuits are created</span>
        <span class="k">return</span> <span class="kc">None</span>

    <span class="nd">@property</span>
    <span class="k">def</span> <span class="nf">model_units</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="sd">&quot;&quot;&quot;Model units.</span>

<span class="sd">        References</span>
<span class="sd">        ----------</span>

<span class="sd">        &gt;&gt;&gt; oEditor.GetActiveUnits</span>
<span class="sd">        &gt;&gt;&gt; oEditor.SetActiveUnits</span>
<span class="sd">        &quot;&quot;&quot;</span>
        <span class="k">return</span> <span class="n">_retry_ntimes</span><span class="p">(</span><span class="mi">10</span><span class="p">,</span> <span class="bp">self</span><span class="o">.</span><span class="n">layouteditor</span><span class="o">.</span><span class="n">GetActiveUnits</span><span class="p">)</span>

    <span class="nd">@property</span>
    <span class="k">def</span> <span class="nf">layout</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="sd">&quot;&quot;&quot;Primitives.</span>

<span class="sd">        Returns</span>
<span class="sd">        -------</span>
<span class="sd">        :class:`pyaedt.modeler.Primitives3DLayout.Primitives3DLayout`</span>

<span class="sd">        &quot;&quot;&quot;</span>
        <span class="k">if</span> <span class="bp">self</span><span class="o">.</span><span class="n">_app</span><span class="o">.</span><span class="n">design_type</span> <span class="o">==</span> <span class="s2">&quot;Twin Builder&quot;</span><span class="p">:</span>
            <span class="k">return</span>
        <span class="k">return</span> <span class="bp">self</span><span class="o">.</span><span class="n">_primitives</span>

    <span class="nd">@property</span>
    <span class="k">def</span> <span class="nf">primitives</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="sd">&quot;&quot;&quot;Primitives.</span>

<span class="sd">        .. deprecated:: 0.4.13</span>
<span class="sd">           Use :func:`Circuit.modeler.layout` instead.</span>

<span class="sd">        Returns</span>
<span class="sd">        -------</span>
<span class="sd">        :class:`pyaedt.modeler.Primitives3DLayout.Primitives3DLayout`</span>

<span class="sd">        &quot;&quot;&quot;</span>
        <span class="k">return</span> <span class="bp">self</span><span class="o">.</span><span class="n">_primitives</span>

    <span class="nd">@model_units</span><span class="o">.</span><span class="n">setter</span>
    <span class="k">def</span> <span class="nf">model_units</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">units</span><span class="p">):</span>
        <span class="k">assert</span> <span class="n">units</span> <span class="ow">in</span> <span class="n">AEDT_UNITS</span><span class="p">[</span><span class="s2">&quot;Length&quot;</span><span class="p">],</span> <span class="s2">&quot;Invalid units string </span><span class="si">{0}</span><span class="s2">&quot;</span><span class="o">.</span><span class="n">format</span><span class="p">(</span><span class="n">units</span><span class="p">)</span>
        <span class="sd">&quot;&quot;&quot; Set the model units as a string e.g. &quot;mm&quot; &quot;&quot;&quot;</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">oeditor</span><span class="o">.</span><span class="n">SetActivelUnits</span><span class="p">([</span><span class="s2">&quot;NAME:Units Parameter&quot;</span><span class="p">,</span> <span class="s2">&quot;Units:=&quot;</span><span class="p">,</span> <span class="n">units</span><span class="p">,</span> <span class="s2">&quot;Rescale:=&quot;</span><span class="p">,</span> <span class="kc">False</span><span class="p">])</span>

<div class="viewcode-block" id="ModelerNexxim.move"><a class="viewcode-back" href="../../../API/_autosummary/pyaedt.modeler.Circuit.ModelerNexxim.move.html#pyaedt.modeler.Circuit.ModelerNexxim.move">[docs]</a>    <span class="nd">@pyaedt_function_handler</span><span class="p">()</span>
    <span class="k">def</span> <span class="nf">move</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">selections</span><span class="p">,</span> <span class="n">pos</span><span class="p">,</span> <span class="n">units</span><span class="o">=</span><span class="s2">&quot;meter&quot;</span><span class="p">):</span>
        <span class="sd">&quot;&quot;&quot;Move the selections by ``[x, y]``.</span>

<span class="sd">        Parameters</span>
<span class="sd">        ----------</span>
<span class="sd">        selections : list</span>
<span class="sd">            List of the selections.</span>
<span class="sd">        pos : list</span>
<span class="sd">            Offset for the ``[x, y]`` axis.</span>
<span class="sd">        units : str</span>
<span class="sd">            Offset for the Y axis.</span>

<span class="sd">        Returns</span>
<span class="sd">        -------</span>
<span class="sd">        bool</span>
<span class="sd">            ``True`` when successful, ``False`` when failed.</span>

<span class="sd">        References</span>
<span class="sd">        ----------</span>

<span class="sd">        &gt;&gt;&gt; oEditor.Move</span>
<span class="sd">        &quot;&quot;&quot;</span>
        <span class="n">sels</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">_get_components_selections</span><span class="p">(</span><span class="n">selections</span><span class="p">)</span>
        <span class="k">if</span> <span class="ow">not</span> <span class="n">sels</span><span class="p">:</span>
            <span class="bp">self</span><span class="o">.</span><span class="n">logger</span><span class="o">.</span><span class="n">error</span><span class="p">(</span><span class="s2">&quot;No Component Found.&quot;</span><span class="p">)</span>
            <span class="k">return</span> <span class="kc">False</span>
        <span class="n">x_location</span> <span class="o">=</span> <span class="n">AEDT_UNITS</span><span class="p">[</span><span class="s2">&quot;Length&quot;</span><span class="p">][</span><span class="n">units</span><span class="p">]</span> <span class="o">*</span> <span class="nb">float</span><span class="p">(</span><span class="n">pos</span><span class="p">[</span><span class="mi">0</span><span class="p">])</span>
        <span class="n">y_location</span> <span class="o">=</span> <span class="n">AEDT_UNITS</span><span class="p">[</span><span class="s2">&quot;Length&quot;</span><span class="p">][</span><span class="n">units</span><span class="p">]</span> <span class="o">*</span> <span class="nb">float</span><span class="p">(</span><span class="n">pos</span><span class="p">[</span><span class="mi">1</span><span class="p">])</span>

        <span class="bp">self</span><span class="o">.</span><span class="n">oeditor</span><span class="o">.</span><span class="n">Move</span><span class="p">(</span>
            <span class="p">[</span><span class="s2">&quot;NAME:Selections&quot;</span><span class="p">,</span> <span class="s2">&quot;Selections:=&quot;</span><span class="p">,</span> <span class="n">sels</span><span class="p">],</span>
            <span class="p">[</span>
                <span class="s2">&quot;NAME:MoveParameters&quot;</span><span class="p">,</span>
                <span class="s2">&quot;xdelta:=&quot;</span><span class="p">,</span>
                <span class="n">x_location</span><span class="p">,</span>
                <span class="s2">&quot;ydelta:=&quot;</span><span class="p">,</span>
                <span class="n">y_location</span><span class="p">,</span>
                <span class="s2">&quot;Disconnect:=&quot;</span><span class="p">,</span>
                <span class="kc">False</span><span class="p">,</span>
                <span class="s2">&quot;Rubberband:=&quot;</span><span class="p">,</span>
                <span class="kc">False</span><span class="p">,</span>
            <span class="p">],</span>
        <span class="p">)</span>
        <span class="k">return</span> <span class="kc">True</span></div>

<div class="viewcode-block" id="ModelerNexxim.rotate"><a class="viewcode-back" href="../../../API/_autosummary/pyaedt.modeler.Circuit.ModelerNexxim.rotate.html#pyaedt.modeler.Circuit.ModelerNexxim.rotate">[docs]</a>    <span class="nd">@pyaedt_function_handler</span><span class="p">()</span>
    <span class="k">def</span> <span class="nf">rotate</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">selections</span><span class="p">,</span> <span class="n">degrees</span><span class="o">=</span><span class="mi">90</span><span class="p">):</span>
        <span class="sd">&quot;&quot;&quot;Rotate the selections by degrees.</span>

<span class="sd">        Parameters</span>
<span class="sd">        ----------</span>
<span class="sd">        selections : list</span>
<span class="sd">            List of the selections.</span>
<span class="sd">        degrees : optional</span>
<span class="sd">            Angle rotation in degrees. The default is ``90``.</span>

<span class="sd">        Returns</span>
<span class="sd">        -------</span>
<span class="sd">        bool</span>
<span class="sd">            ``True`` when successful, ``False`` when failed.</span>

<span class="sd">        References</span>
<span class="sd">        ----------</span>

<span class="sd">        &gt;&gt;&gt; oEditor.Rotate</span>
<span class="sd">        &quot;&quot;&quot;</span>
        <span class="n">sels</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">_get_components_selections</span><span class="p">(</span><span class="n">selections</span><span class="p">)</span>
        <span class="k">if</span> <span class="ow">not</span> <span class="n">sels</span><span class="p">:</span>
            <span class="bp">self</span><span class="o">.</span><span class="n">logger</span><span class="o">.</span><span class="n">error</span><span class="p">(</span><span class="s2">&quot;No Component Found.&quot;</span><span class="p">)</span>
            <span class="k">return</span> <span class="kc">False</span>

        <span class="bp">self</span><span class="o">.</span><span class="n">oeditor</span><span class="o">.</span><span class="n">Rotate</span><span class="p">(</span>
            <span class="p">[</span><span class="s2">&quot;NAME:Selections&quot;</span><span class="p">,</span> <span class="s2">&quot;Selections:=&quot;</span><span class="p">,</span> <span class="n">sels</span><span class="p">],</span>
            <span class="p">[</span>
                <span class="s2">&quot;NAME:RotateParameters&quot;</span><span class="p">,</span>
                <span class="s2">&quot;Degrees:=&quot;</span><span class="p">,</span>
                <span class="n">degrees</span><span class="p">,</span>
                <span class="s2">&quot;Disconnect:=&quot;</span><span class="p">,</span>
                <span class="kc">False</span><span class="p">,</span>
                <span class="s2">&quot;Rubberband:=&quot;</span><span class="p">,</span>
                <span class="kc">False</span><span class="p">,</span>
            <span class="p">],</span>
        <span class="p">)</span>
        <span class="k">return</span> <span class="kc">True</span></div></div>


<div class="viewcode-block" id="ModelerTwinBuilder"><a class="viewcode-back" href="../../../API/_autosummary/pyaedt.modeler.Circuit.ModelerTwinBuilder.html#pyaedt.modeler.Circuit.ModelerTwinBuilder">[docs]</a><span class="k">class</span> <span class="nc">ModelerTwinBuilder</span><span class="p">(</span><span class="n">ModelerCircuit</span><span class="p">):</span>
    <span class="sd">&quot;&quot;&quot;ModelerTwinBuilder class.</span>

<span class="sd">    Parameters</span>
<span class="sd">    ----------</span>
<span class="sd">    app : :class:`pyaedt.application.AnalysisTwinBuilder.AnalysisTwinBuilder`</span>

<span class="sd">    &quot;&quot;&quot;</span>

    <span class="k">def</span> <span class="fm">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">app</span><span class="p">):</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">_app</span> <span class="o">=</span> <span class="n">app</span>
        <span class="n">ModelerCircuit</span><span class="o">.</span><span class="fm">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">app</span><span class="p">)</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">_components</span> <span class="o">=</span> <span class="n">TwinBuilderComponents</span><span class="p">(</span><span class="bp">self</span><span class="p">)</span>

    <span class="nd">@property</span>
    <span class="k">def</span> <span class="nf">components</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="sd">&quot;&quot;&quot;</span>
<span class="sd">        .. deprecated:: 0.4.13</span>
<span class="sd">           Use :func:`TwinBuilder.modeler.schematic` instead.</span>

<span class="sd">        &quot;&quot;&quot;</span>
        <span class="k">return</span> <span class="bp">self</span><span class="o">.</span><span class="n">_components</span>

    <span class="nd">@property</span>
    <span class="k">def</span> <span class="nf">schematic</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="sd">&quot;&quot;&quot;Schematic Object.</span>

<span class="sd">        Returns</span>
<span class="sd">        -------</span>
<span class="sd">        :class:`pyaedt.modeler.PrimitivesTwinBuilder.TwinBuilderComponents`</span>

<span class="sd">        &quot;&quot;&quot;</span>
        <span class="k">return</span> <span class="bp">self</span><span class="o">.</span><span class="n">_components</span></div>


<div class="viewcode-block" id="ModelerEmit"><a class="viewcode-back" href="../../../API/_autosummary/pyaedt.modeler.Circuit.ModelerEmit.html#pyaedt.modeler.Circuit.ModelerEmit">[docs]</a><span class="k">class</span> <span class="nc">ModelerEmit</span><span class="p">(</span><span class="n">ModelerCircuit</span><span class="p">):</span>
    <span class="sd">&quot;&quot;&quot;ModelerEmit class.</span>

<span class="sd">    Parameters</span>
<span class="sd">    ----------</span>
<span class="sd">    app : :class:`pyaedt.application.AnalysisEmit`</span>

<span class="sd">    &quot;&quot;&quot;</span>

    <span class="k">def</span> <span class="fm">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">app</span><span class="p">):</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">_app</span> <span class="o">=</span> <span class="n">app</span>
        <span class="n">ModelerCircuit</span><span class="o">.</span><span class="fm">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">app</span><span class="p">)</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">components</span> <span class="o">=</span> <span class="n">EmitComponents</span><span class="p">(</span><span class="n">app</span><span class="p">,</span> <span class="bp">self</span><span class="p">)</span></div>


<span class="k">class</span> <span class="nc">ModelerMaxwellCircuit</span><span class="p">(</span><span class="n">ModelerCircuit</span><span class="p">):</span>
    <span class="sd">&quot;&quot;&quot;ModelerMaxwellCircuit class.</span>

<span class="sd">    Parameters</span>
<span class="sd">    ----------</span>
<span class="sd">    app : :class:`pyaedt.application.AnalysisMaxwellCircuit`</span>

<span class="sd">    &quot;&quot;&quot;</span>

    <span class="k">def</span> <span class="fm">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">app</span><span class="p">):</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">_app</span> <span class="o">=</span> <span class="n">app</span>
        <span class="n">ModelerCircuit</span><span class="o">.</span><span class="fm">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">app</span><span class="p">)</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">_components</span> <span class="o">=</span> <span class="n">MaxwellCircuitComponents</span><span class="p">(</span><span class="bp">self</span><span class="p">)</span>

    <span class="nd">@property</span>
    <span class="k">def</span> <span class="nf">schematic</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="sd">&quot;&quot;&quot;Schematic Object.</span>

<span class="sd">        Returns</span>
<span class="sd">        -------</span>
<span class="sd">        :class:`pyaedt.modeler.PrimitivesMaxwellCircuit.MaxwellCircuitComponents`</span>

<span class="sd">        &quot;&quot;&quot;</span>
        <span class="k">return</span> <span class="bp">self</span><span class="o">.</span><span class="n">_components</span>
</pre></div>

              </article>
              

              
          </div>
          
      </div>
    </div>

  
  
  <!-- Scripts loaded after <body> so the DOM is not blocked -->
  <script src="../../../_static/scripts/pydata-sphinx-theme.js?digest=92025949c220c2e29695"></script>

<footer class="bd-footer"><div class="bd-footer__inner container">
  
  <div class="footer-item">
    <p class="copyright">
    &copy; Copyright (c) 2022 ANSYS, Inc. All rights reserved.<br>
</p>
  </div>
  
  <div class="footer-item">
    <p class="sphinx-version">
Created using <a href="http://sphinx-doc.org/">Sphinx</a> 5.3.0.<br>
</p>
  </div>
  
</div>
</footer>
  </body>
</html>