
<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>pyaedt.modeler.Primitives2D &#8212; PyAEDT</title>
    
<script>
  document.documentElement.dataset.mode = localStorage.getItem("mode") || "";
  document.documentElement.dataset.theme = localStorage.getItem("theme") || "light"
</script>

  <!-- Loaded before other Sphinx assets -->
  <link href="../../../_static/styles/theme.css?digest=92025949c220c2e29695" rel="stylesheet">
<link href="../../../_static/styles/pydata-sphinx-theme.css?digest=92025949c220c2e29695" rel="stylesheet">


  <link rel="stylesheet"
    href="../../../_static/vendor/fontawesome/5.13.0/css/all.min.css">
  <link rel="preload" as="font" type="font/woff2" crossorigin
    href="../../../_static/vendor/fontawesome/5.13.0/webfonts/fa-solid-900.woff2">
  <link rel="preload" as="font" type="font/woff2" crossorigin
    href="../../../_static/vendor/fontawesome/5.13.0/webfonts/fa-brands-400.woff2">

    <link rel="stylesheet" type="text/css" href="../../../_static/pygments.css" />
    <link rel="stylesheet" type="text/css" href="../../../_static/copybutton.css" />
    <link rel="stylesheet" type="text/css" href="../../../_static/graphviz.css" />
    <link rel="stylesheet" type="text/css" href="../../../_static/css\ansys_sphinx_theme.css" />
    <link rel="stylesheet" type="text/css" href="../../../_static/sg_gallery.css" />
    <link rel="stylesheet" type="text/css" href="../../../_static/sg_gallery-binder.css" />
    <link rel="stylesheet" type="text/css" href="../../../_static/sg_gallery-dataframe.css" />
    <link rel="stylesheet" type="text/css" href="../../../_static/sg_gallery-rendered-html.css" />

  <!-- Pre-loaded scripts that we'll load fully later -->
  <link rel="preload" as="script" href="../../../_static/scripts/pydata-sphinx-theme.js?digest=92025949c220c2e29695">

    
        <link href="../../../_static/css/breadcrumbs.css" rel="stylesheet">
    
    <script data-url_root="../../../" id="documentation_options" src="../../../_static/documentation_options.js"></script>
    <script src="../../../_static/jquery.js"></script>
    <script src="../../../_static/underscore.js"></script>
    <script src="../../../_static/_sphinx_javascript_frameworks_compat.js"></script>
    <script src="../../../_static/doctools.js"></script>
    <script src="../../../_static/sphinx_highlight.js"></script>
    <script src="../../../_static/clipboard.min.js"></script>
    <script src="../../../_static/copybutton.js"></script>
    <link rel="shortcut icon" href="../../../_static/ansys-favicon.png"/>
    <link rel="index" title="Index" href="../../../genindex.html" />
    <link rel="search" title="Search" href="../../../search.html" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="docsearch:language" content="en">
  </head>
  
  
  <body data-spy="scroll" data-target="#bd-toc-nav" data-offset="180" data-default-mode="">
    <div class="bd-header-announcement container-fluid" id="banner">
      

    </div>

    
    
    <nav class="bd-header navbar navbar-light navbar-expand-lg bg-light fixed-top bd-navbar" id="navbar-main"><div class="bd-header__inner container-xl">

  <div id="navbar-start">
    
    
  


<a class="navbar-brand logo" href="../../../index.html">
  
  
  
  
    <img src="../../../_static/pyansys-logo-black-cropped.png" class="logo__image only-light" alt="Logo image">
    <img src="../../../_static/pyansys-logo-black-cropped.png" class="logo__image only-dark" alt="Logo image">
  
  
</a>
    
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapsible" aria-controls="navbar-collapsible" aria-expanded="false" aria-label="Toggle navigation">
    <span class="fas fa-bars"></span>
  </button>

  
  <div id="navbar-collapsible" class="col-lg-9 collapse navbar-collapse">
    <div id="navbar-center" class="mr-auto">
      
      <div class="navbar-center-item">
        <ul id="navbar-main-elements" class="navbar-nav">
    <li class="toctree-l1 nav-item">
 <a class="reference internal nav-link" href="../../../Getting_started/index.html">
  Getting started
 </a>
</li>

<li class="toctree-l1 nav-item">
 <a class="reference internal nav-link" href="../../../User_guide/index.html">
  User guide
 </a>
</li>

<li class="toctree-l1 nav-item">
 <a class="reference internal nav-link" href="../../../API/index.html">
  API reference
 </a>
</li>

<li class="toctree-l1 nav-item">
 <a class="reference internal nav-link" href="../../../examples/index.html">
  Examples
 </a>
</li>

<li class="toctree-l1 nav-item">
 <a class="reference internal nav-link" href="../../../Contributing.html">
  Contribute
 </a>
</li>

    
</ul>
      </div>
      
    </div>

    <div id="navbar-end">
      
      <div class="navbar-end-item">
        <span id="theme-switch" class="btn btn-sm btn-outline-primary navbar-btn rounded-circle">
    <a class="theme-switch" data-mode="light"><i class="fas fa-sun"></i></a>
    <a class="theme-switch" data-mode="dark"><i class="far fa-moon"></i></a>
    <a class="theme-switch" data-mode="auto"><i class="fas fa-adjust"></i></a>
</span>
      </div>
      
      <div class="navbar-end-item">
        <ul id="navbar-icon-links" class="navbar-nav" aria-label="Icon Links">
        <li class="nav-item">
          <a class="nav-link" href="https://github.com/pyansys/pyaedt" rel="noopener" target="_blank" title="GitHub"><span><i class="fab fa-github-square"></i></span>
            <label class="sr-only">GitHub</label></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="https://github.com/pyansys/pyaedt/discussions" rel="noopener" target="_blank" title="Support"><span><i class="fa fa-comment fa-fw"></i></span>
            <label class="sr-only">Support</label></a>
        </li>
      </ul>
      </div>
      
    </div>
  </div>
</div>
    </nav>
    
    
    
        <div class="container-xl">
    <div class="row">
        <div class="col-12 col-md-3" id="breadcrumbs-spacer"></div>
        <div class="col-12 col-md-11 col-xl-9" id="breadcrumbs">
          
    <div class="related" role="navigation" aria-label="related navigation">
      <h3>Navigation</h3>
      <ul>
    
        <li class="nav-item nav-item-additional-breadcrumb"><a href="https://docs.pyansys.com/">PyAnsys</a> » </li>
    
    
        <li class="nav-item nav-item-0"><a href="../../../index.html">PyAEDT</a> » </li>
    

          <li class="nav-item nav-item-1"><a href="../../index.html" accesskey="U">Module code</a> » </li>
        <li class="nav-item nav-item-this"><a href="">pyaedt.modeler.Primitives2D</a></li> 
      </ul>
    </div>
        </div>
  </div>
</div>
    


    <div class="bd-container container-xl">
      <div class="bd-container__inner row">
          

<!-- Only show if we have sidebars configured, else just a small margin  -->
<div class="bd-sidebar-primary col-12 col-md-3 bd-sidebar">
  <div class="sidebar-start-items"><form class="bd-search d-flex align-items-center" action="../../../search.html" method="get">
  <i class="icon fas fa-search"></i>
  <input type="search" class="form-control" name="q" id="search-input" placeholder="Search the docs ..." aria-label="Search the docs ..." autocomplete="off" >
</form><nav class="bd-links" id="bd-docs-nav" aria-label="Main navigation">
  <div class="bd-toc-item active">
    
    
    
  </div>
</nav>
  </div>
  <div class="sidebar-end-items">
  </div>
</div>


          


<div class="bd-sidebar-secondary d-none d-xl-block col-xl-2 bd-toc">
  
</div>


          
          
          <div class="bd-content col-12 col-md-9 col-xl-7">
              
              <article class="bd-article" role="main">
                
  <h1>Source code for pyaedt.modeler.Primitives2D</h1><div class="highlight"><pre>
<span></span><span class="kn">from</span> <span class="nn">pyaedt.generic.general_methods</span> <span class="kn">import</span> <span class="n">pyaedt_function_handler</span>
<span class="kn">from</span> <span class="nn">pyaedt.modeler.Primitives</span> <span class="kn">import</span> <span class="n">Primitives</span>


<div class="viewcode-block" id="Primitives2D"><a class="viewcode-back" href="../../../API/_autosummary/pyaedt.modeler.Primitives2D.Primitives2D.html#pyaedt.modeler.Primitives2D.Primitives2D">[docs]</a><span class="k">class</span> <span class="nc">Primitives2D</span><span class="p">(</span><span class="n">Primitives</span><span class="p">,</span> <span class="nb">object</span><span class="p">):</span>
    <span class="sd">&quot;&quot;&quot;Manages primitives in 2D tools.</span>

<span class="sd">    This class is inherited in the caller application and is accessible through the primitives variable part</span>
<span class="sd">    of the modeler object (for example, ``hfss.modeler`` or ``icepak.modeler``).</span>


<span class="sd">    Examples</span>
<span class="sd">    --------</span>
<span class="sd">    Basic usage demonstrated with a Q2D or Maxwell 2D design:</span>

<span class="sd">    &gt;&gt;&gt; from pyaedt import Q2d</span>
<span class="sd">    &gt;&gt;&gt; aedtapp = Q2d()</span>
<span class="sd">    &gt;&gt;&gt; prim = aedtapp.modeler</span>
<span class="sd">    &quot;&quot;&quot;</span>

    <span class="nd">@property</span>
    <span class="k">def</span> <span class="nf">plane2d</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="sd">&quot;&quot;&quot;Create a 2D plane.&quot;&quot;&quot;</span>
        <span class="n">plane</span> <span class="o">=</span> <span class="s2">&quot;Z&quot;</span>
        <span class="k">if</span> <span class="bp">self</span><span class="o">.</span><span class="n">_app</span><span class="o">.</span><span class="n">design_type</span> <span class="o">==</span> <span class="s2">&quot;Maxwell 2D&quot;</span><span class="p">:</span>
            <span class="k">if</span> <span class="bp">self</span><span class="o">.</span><span class="n">_app</span><span class="o">.</span><span class="n">_odesign</span><span class="o">.</span><span class="n">GetGeometryMode</span><span class="p">()</span> <span class="o">==</span> <span class="s2">&quot;about Z&quot;</span><span class="p">:</span>
                <span class="n">plane</span> <span class="o">=</span> <span class="s2">&quot;Y&quot;</span>
        <span class="k">return</span> <span class="n">plane</span>

    <span class="k">def</span> <span class="fm">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="n">Primitives</span><span class="o">.</span><span class="fm">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">)</span>

<div class="viewcode-block" id="Primitives2D.create_circle"><a class="viewcode-back" href="../../../API/_autosummary/pyaedt.modeler.Primitives2D.Primitives2D.create_circle.html#pyaedt.modeler.Primitives2D.Primitives2D.create_circle">[docs]</a>    <span class="nd">@pyaedt_function_handler</span><span class="p">()</span>
    <span class="k">def</span> <span class="nf">create_circle</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">position</span><span class="p">,</span> <span class="n">radius</span><span class="p">,</span> <span class="n">num_sides</span><span class="o">=</span><span class="mi">0</span><span class="p">,</span> <span class="n">is_covered</span><span class="o">=</span><span class="kc">True</span><span class="p">,</span> <span class="n">name</span><span class="o">=</span><span class="kc">None</span><span class="p">,</span> <span class="n">matname</span><span class="o">=</span><span class="kc">None</span><span class="p">):</span>
        <span class="sd">&quot;&quot;&quot;Create a circle.</span>

<span class="sd">        Parameters</span>
<span class="sd">        ----------</span>
<span class="sd">        position : list</span>
<span class="sd">            ApplicationName.modeler.Position(x,y,z) object</span>
<span class="sd">        radius : float</span>
<span class="sd">            Radius of the object.</span>
<span class="sd">        numSides : int, optional</span>
<span class="sd">            Number of sides. The default is ``0``, which is correct for a circle.</span>
<span class="sd">        is_covered : bool</span>
<span class="sd">            Specify whether the ellipse is a sheet (covered) or a line object</span>
<span class="sd">        name : str, optional</span>
<span class="sd">            Name of the object. The default is ``None``. If ``None`` ,</span>
<span class="sd">            a unique name ``&quot;NewObject_xxxxxx&quot;`` will be assigned)</span>
<span class="sd">        matname : str, optional</span>
<span class="sd">            Name of the material. The default is ``None``. If ``None``,</span>
<span class="sd">            the default material is assigned.</span>

<span class="sd">        Returns</span>
<span class="sd">        -------</span>
<span class="sd">        pyaedt.modeler.Object3d.Object3d</span>
<span class="sd">            Object3d</span>

<span class="sd">        References</span>
<span class="sd">        ----------</span>

<span class="sd">        &gt;&gt;&gt; oEditor.CreateCircle</span>

<span class="sd">        Examples</span>
<span class="sd">        --------</span>
<span class="sd">        &gt;&gt;&gt; circle1 = aedtapp.modeler.create_circle([0, -2, -2], 3)</span>
<span class="sd">        &gt;&gt;&gt; circle2 = aedtapp.modeler.create_circle(position=[0, -2, -2], radius=3, num_sides=6,</span>
<span class="sd">        ...                                         name=&quot;MyCircle&quot;, matname=&quot;Copper&quot;)</span>


<span class="sd">        &quot;&quot;&quot;</span>
        <span class="n">szAxis</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">plane2d</span>
        <span class="n">XCenter</span><span class="p">,</span> <span class="n">YCenter</span><span class="p">,</span> <span class="n">ZCenter</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">_pos_with_arg</span><span class="p">(</span><span class="n">position</span><span class="p">)</span>
        <span class="n">Radius</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">_arg_with_dim</span><span class="p">(</span><span class="n">radius</span><span class="p">)</span>

        <span class="n">vArg1</span> <span class="o">=</span> <span class="p">[</span><span class="s2">&quot;NAME:CircleParameters&quot;</span><span class="p">]</span>
        <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">&quot;IsCovered:=&quot;</span><span class="p">),</span> <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="n">is_covered</span><span class="p">)</span>
        <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">&quot;XCenter:=&quot;</span><span class="p">),</span> <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="n">XCenter</span><span class="p">)</span>
        <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">&quot;YCenter:=&quot;</span><span class="p">),</span> <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="n">YCenter</span><span class="p">)</span>
        <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">&quot;ZCenter:=&quot;</span><span class="p">),</span> <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="n">ZCenter</span><span class="p">)</span>
        <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">&quot;Radius:=&quot;</span><span class="p">),</span> <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="n">Radius</span><span class="p">)</span>
        <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">&quot;WhichAxis:=&quot;</span><span class="p">),</span> <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="n">szAxis</span><span class="p">)</span>
        <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">&quot;NumSegments:=&quot;</span><span class="p">),</span> <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">&quot;</span><span class="si">{}</span><span class="s2">&quot;</span><span class="o">.</span><span class="n">format</span><span class="p">(</span><span class="n">num_sides</span><span class="p">))</span>

        <span class="n">vArg2</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">_default_object_attributes</span><span class="p">(</span><span class="n">name</span><span class="o">=</span><span class="n">name</span><span class="p">,</span> <span class="n">matname</span><span class="o">=</span><span class="n">matname</span><span class="p">)</span>
        <span class="n">new_object_name</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">oeditor</span><span class="o">.</span><span class="n">CreateCircle</span><span class="p">(</span><span class="n">vArg1</span><span class="p">,</span> <span class="n">vArg2</span><span class="p">)</span>
        <span class="k">return</span> <span class="bp">self</span><span class="o">.</span><span class="n">_create_object</span><span class="p">(</span><span class="n">new_object_name</span><span class="p">)</span></div>

<div class="viewcode-block" id="Primitives2D.create_ellipse"><a class="viewcode-back" href="../../../API/_autosummary/pyaedt.modeler.Primitives2D.Primitives2D.create_ellipse.html#pyaedt.modeler.Primitives2D.Primitives2D.create_ellipse">[docs]</a>    <span class="nd">@pyaedt_function_handler</span><span class="p">()</span>
    <span class="k">def</span> <span class="nf">create_ellipse</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">position</span><span class="p">,</span> <span class="n">major_radius</span><span class="p">,</span> <span class="n">ratio</span><span class="p">,</span> <span class="n">is_covered</span><span class="o">=</span><span class="kc">True</span><span class="p">,</span> <span class="n">name</span><span class="o">=</span><span class="kc">None</span><span class="p">,</span> <span class="n">matname</span><span class="o">=</span><span class="kc">None</span><span class="p">):</span>
        <span class="sd">&quot;&quot;&quot;Create an ellipse.</span>

<span class="sd">        Parameters</span>
<span class="sd">        ----------</span>
<span class="sd">        position : list of float</span>
<span class="sd">            Center Position of the ellipse</span>
<span class="sd">        major_radius : flost</span>
<span class="sd">            Length of the major axis of the ellipse</span>
<span class="sd">        ratio : float</span>
<span class="sd">            Ratio of the major axis to the minor axis of the ellipse</span>
<span class="sd">        is_covered : bool</span>
<span class="sd">            Specify whether the ellipse is a sheet (covered) or a line object</span>
<span class="sd">        name : str, default=None</span>
<span class="sd">            Name of the object. The default is ``None``. If ``None`` ,</span>
<span class="sd">            a unique name NewObject_xxxxxx will be assigned)</span>
<span class="sd">        matname : str, default=None</span>
<span class="sd">             Name of the material. The default is ``None``. If ``None``,</span>
<span class="sd">             the default material is assigned.</span>

<span class="sd">        Returns</span>
<span class="sd">        -------</span>
<span class="sd">        pyaedt.modeler.Object3d.Object3d</span>
<span class="sd">            Object3d</span>

<span class="sd">        References</span>
<span class="sd">        ----------</span>

<span class="sd">        &gt;&gt;&gt; oEditor.CreateEllipse</span>

<span class="sd">        Examples</span>
<span class="sd">        --------</span>
<span class="sd">        &gt;&gt;&gt; ellipse1 = aedtapp.modeler.create_ellipse([0, -2, -2], 4.0, 0.2)</span>
<span class="sd">        &gt;&gt;&gt; ellipse2 = aedtapp.modeler.create_ellipse(position=[0, -2, -2], major_radius=4.0, ratio=0.2,</span>
<span class="sd">        ...                                           name=&quot;MyEllipse&quot;, matname=&quot;Copper&quot;)</span>
<span class="sd">        &quot;&quot;&quot;</span>
        <span class="n">szAxis</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">plane2d</span>
        <span class="n">XStart</span><span class="p">,</span> <span class="n">YStart</span><span class="p">,</span> <span class="n">ZStart</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">_pos_with_arg</span><span class="p">(</span><span class="n">position</span><span class="p">)</span>

        <span class="n">vArg1</span> <span class="o">=</span> <span class="p">[</span><span class="s2">&quot;NAME:EllipseParameters&quot;</span><span class="p">]</span>
        <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">&quot;IsCovered:=&quot;</span><span class="p">),</span> <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="n">is_covered</span><span class="p">)</span>
        <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">&quot;XCenter:=&quot;</span><span class="p">),</span> <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="n">XStart</span><span class="p">)</span>
        <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">&quot;YCenter:=&quot;</span><span class="p">),</span> <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="n">YStart</span><span class="p">)</span>
        <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">&quot;ZCenter:=&quot;</span><span class="p">),</span> <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="n">ZStart</span><span class="p">)</span>
        <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">&quot;MajRadius:=&quot;</span><span class="p">),</span> <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="bp">self</span><span class="o">.</span><span class="n">_arg_with_dim</span><span class="p">(</span><span class="n">major_radius</span><span class="p">))</span>
        <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">&quot;Ratio:=&quot;</span><span class="p">),</span> <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="n">ratio</span><span class="p">)</span>
        <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">&quot;WhichAxis:=&quot;</span><span class="p">),</span> <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="n">szAxis</span><span class="p">)</span>

        <span class="n">vArg2</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">_default_object_attributes</span><span class="p">(</span><span class="n">name</span><span class="o">=</span><span class="n">name</span><span class="p">,</span> <span class="n">matname</span><span class="o">=</span><span class="n">matname</span><span class="p">)</span>
        <span class="n">new_object_name</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">oeditor</span><span class="o">.</span><span class="n">CreateEllipse</span><span class="p">(</span><span class="n">vArg1</span><span class="p">,</span> <span class="n">vArg2</span><span class="p">)</span>
        <span class="k">return</span> <span class="bp">self</span><span class="o">.</span><span class="n">_create_object</span><span class="p">(</span><span class="n">new_object_name</span><span class="p">)</span></div>

<div class="viewcode-block" id="Primitives2D.create_rectangle"><a class="viewcode-back" href="../../../API/_autosummary/pyaedt.modeler.Primitives2D.Primitives2D.create_rectangle.html#pyaedt.modeler.Primitives2D.Primitives2D.create_rectangle">[docs]</a>    <span class="nd">@pyaedt_function_handler</span><span class="p">()</span>
    <span class="k">def</span> <span class="nf">create_rectangle</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">position</span><span class="p">,</span> <span class="n">dimension_list</span><span class="p">,</span> <span class="n">is_covered</span><span class="o">=</span><span class="kc">True</span><span class="p">,</span> <span class="n">name</span><span class="o">=</span><span class="kc">None</span><span class="p">,</span> <span class="n">matname</span><span class="o">=</span><span class="kc">None</span><span class="p">):</span>
        <span class="sd">&quot;&quot;&quot;Create a rectangle.</span>

<span class="sd">        Parameters</span>
<span class="sd">        ----------</span>
<span class="sd">        position : list of float</span>
<span class="sd">            Position of the lower-left corner of the rectangle</span>
<span class="sd">        dimension_list : list of float</span>
<span class="sd">            List of rectangle sizes: [X size, Y size] for XY planes or [Z size, R size] for RZ planes</span>
<span class="sd">        is_covered : bool</span>
<span class="sd">            Specify whether the ellipse is a sheet (covered) or a line object</span>
<span class="sd">        name : str, default=None</span>
<span class="sd">            Name of the object. The default is ``None``. If ``None`` ,</span>
<span class="sd">            a unique name NewObject_xxxxxx will be assigned)</span>
<span class="sd">        matname : str, default=None</span>
<span class="sd">             Name of the material. The default is ``None``. If ``None``,</span>
<span class="sd">             the default material is assigned.</span>

<span class="sd">        Returns</span>
<span class="sd">        -------</span>
<span class="sd">        :class:`pyaedt.modeler.Object3d.Object3d`</span>

<span class="sd">        References</span>
<span class="sd">        ----------</span>

<span class="sd">        &gt;&gt;&gt; oEditor.CreateRectangle</span>

<span class="sd">        Examples</span>
<span class="sd">        --------</span>

<span class="sd">        &gt;&gt;&gt; rect1 = aedtapp.modeler.create_rectangle([0, -2, -2], [3, 4])</span>
<span class="sd">        &gt;&gt;&gt; rect2 = aedtapp.modeler.create_rectangle(position=[0, -2, -2], dimension_list=[3, 4],</span>
<span class="sd">        ...                                          name=&quot;MyCircle&quot;, matname=&quot;Copper&quot;)</span>

<span class="sd">        &quot;&quot;&quot;</span>
        <span class="n">axis</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">plane2d</span>
        <span class="n">x_start</span><span class="p">,</span> <span class="n">y_start</span><span class="p">,</span> <span class="n">z_start</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">_pos_with_arg</span><span class="p">(</span><span class="n">position</span><span class="p">)</span>
        <span class="n">width</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">_arg_with_dim</span><span class="p">(</span><span class="n">dimension_list</span><span class="p">[</span><span class="mi">0</span><span class="p">])</span>
        <span class="n">height</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">_arg_with_dim</span><span class="p">(</span><span class="n">dimension_list</span><span class="p">[</span><span class="mi">1</span><span class="p">])</span>

        <span class="n">vArg1</span> <span class="o">=</span> <span class="p">[</span><span class="s2">&quot;NAME:RectangleParameters&quot;</span><span class="p">]</span>
        <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">&quot;IsCovered:=&quot;</span><span class="p">),</span> <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="n">is_covered</span><span class="p">)</span>
        <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">&quot;XStart:=&quot;</span><span class="p">),</span> <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="n">x_start</span><span class="p">)</span>
        <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">&quot;YStart:=&quot;</span><span class="p">),</span> <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="n">y_start</span><span class="p">)</span>
        <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">&quot;ZStart:=&quot;</span><span class="p">),</span> <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="n">z_start</span><span class="p">)</span>
        <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">&quot;Width:=&quot;</span><span class="p">),</span> <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="n">width</span><span class="p">)</span>
        <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">&quot;Height:=&quot;</span><span class="p">),</span> <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="n">height</span><span class="p">)</span>
        <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">&quot;WhichAxis:=&quot;</span><span class="p">),</span> <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="n">axis</span><span class="p">)</span>

        <span class="n">vArg2</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">_default_object_attributes</span><span class="p">(</span><span class="n">name</span><span class="o">=</span><span class="n">name</span><span class="p">,</span> <span class="n">matname</span><span class="o">=</span><span class="n">matname</span><span class="p">)</span>
        <span class="n">new_object_name</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">oeditor</span><span class="o">.</span><span class="n">CreateRectangle</span><span class="p">(</span><span class="n">vArg1</span><span class="p">,</span> <span class="n">vArg2</span><span class="p">)</span>
        <span class="k">return</span> <span class="bp">self</span><span class="o">.</span><span class="n">_create_object</span><span class="p">(</span><span class="n">new_object_name</span><span class="p">)</span></div>

<div class="viewcode-block" id="Primitives2D.create_regular_polygon"><a class="viewcode-back" href="../../../API/_autosummary/pyaedt.modeler.Primitives2D.Primitives2D.create_regular_polygon.html#pyaedt.modeler.Primitives2D.Primitives2D.create_regular_polygon">[docs]</a>    <span class="nd">@pyaedt_function_handler</span><span class="p">()</span>
    <span class="k">def</span> <span class="nf">create_regular_polygon</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">position</span><span class="p">,</span> <span class="n">start_point</span><span class="p">,</span> <span class="n">num_sides</span><span class="o">=</span><span class="mi">6</span><span class="p">,</span> <span class="n">is_covered</span><span class="o">=</span><span class="kc">True</span><span class="p">,</span> <span class="n">name</span><span class="o">=</span><span class="kc">None</span><span class="p">,</span> <span class="n">matname</span><span class="o">=</span><span class="kc">None</span><span class="p">):</span>
        <span class="sd">&quot;&quot;&quot;Create a rectangle.</span>

<span class="sd">        Parameters</span>
<span class="sd">        ----------</span>
<span class="sd">        position : list of float</span>
<span class="sd">            Position of the center of the polygon in ``[x, y, z]``.</span>
<span class="sd">        start_point : list of float</span>
<span class="sd">            Start point for the outer path of the polygon in ``[x, y, z]``.</span>
<span class="sd">        num_sides : int</span>
<span class="sd">            Number of sides of the polygon. Must be an integer &gt;= 3.</span>
<span class="sd">        is_covered : bool</span>
<span class="sd">            Specify whether the ellipse is a sheet (covered) or a line object</span>
<span class="sd">        name : str, default=None</span>
<span class="sd">            Name of the object. The default is ``None``. If ``None`` ,</span>
<span class="sd">            a unique name NewObject_xxxxxx will be assigned)</span>
<span class="sd">        matname : str, default=None</span>
<span class="sd">             Name of the material. The default is ``None``. If ``None``,</span>
<span class="sd">             the default material is assigned.</span>

<span class="sd">        Returns</span>
<span class="sd">        -------</span>
<span class="sd">        pyaedt.modeler.Object3d.Object3d</span>

<span class="sd">        References</span>
<span class="sd">        ----------</span>

<span class="sd">        &gt;&gt;&gt; oEditor.CreateRegularPolygon</span>

<span class="sd">        Examples</span>
<span class="sd">        --------</span>

<span class="sd">        &gt;&gt;&gt; pg1 = aedtapp.modeler.create_regular_polygon([0, 0, 0], [0, 2, 0])</span>
<span class="sd">        &gt;&gt;&gt; pg2 = aedtapp.modeler.create_regular_polygon(position=[0, 0, 0], start_point=[0, 2, 0],</span>
<span class="sd">        ...                                              name=&quot;MyPolygon&quot;, matname=&quot;Copper&quot;)</span>

<span class="sd">        &quot;&quot;&quot;</span>
        <span class="n">x_center</span><span class="p">,</span> <span class="n">y_center</span><span class="p">,</span> <span class="n">z_center</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">_pos_with_arg</span><span class="p">(</span><span class="n">position</span><span class="p">)</span>
        <span class="n">x_start</span><span class="p">,</span> <span class="n">y_start</span><span class="p">,</span> <span class="n">z_start</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">_pos_with_arg</span><span class="p">(</span><span class="n">start_point</span><span class="p">)</span>

        <span class="n">n_sides</span> <span class="o">=</span> <span class="nb">int</span><span class="p">(</span><span class="n">num_sides</span><span class="p">)</span>
        <span class="k">assert</span> <span class="n">n_sides</span> <span class="o">&gt;</span> <span class="mi">2</span>

        <span class="n">vArg1</span> <span class="o">=</span> <span class="p">[</span><span class="s2">&quot;NAME:RegularPolygonParameters&quot;</span><span class="p">]</span>
        <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">&quot;XCenter:=&quot;</span><span class="p">),</span> <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="n">x_center</span><span class="p">)</span>
        <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">&quot;YCenter:=&quot;</span><span class="p">),</span> <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="n">y_center</span><span class="p">)</span>
        <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">&quot;ZCenter:=&quot;</span><span class="p">),</span> <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="n">z_center</span><span class="p">)</span>
        <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">&quot;XStart:=&quot;</span><span class="p">),</span> <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="n">x_start</span><span class="p">)</span>
        <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">&quot;YStart:=&quot;</span><span class="p">),</span> <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="n">y_start</span><span class="p">)</span>
        <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">&quot;ZStart:=&quot;</span><span class="p">),</span> <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="n">z_start</span><span class="p">)</span>

        <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">&quot;NumSides:=&quot;</span><span class="p">),</span> <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="n">n_sides</span><span class="p">)</span>
        <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="s2">&quot;WhichAxis:=&quot;</span><span class="p">),</span> <span class="n">vArg1</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="bp">self</span><span class="o">.</span><span class="n">plane2d</span><span class="p">)</span>

        <span class="n">vArg2</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">_default_object_attributes</span><span class="p">(</span><span class="n">name</span><span class="o">=</span><span class="n">name</span><span class="p">,</span> <span class="n">matname</span><span class="o">=</span><span class="n">matname</span><span class="p">)</span>
        <span class="n">new_object_name</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">oeditor</span><span class="o">.</span><span class="n">CreateRegularPolygon</span><span class="p">(</span><span class="n">vArg1</span><span class="p">,</span> <span class="n">vArg2</span><span class="p">)</span>
        <span class="k">return</span> <span class="bp">self</span><span class="o">.</span><span class="n">_create_object</span><span class="p">(</span><span class="n">new_object_name</span><span class="p">)</span></div>

<div class="viewcode-block" id="Primitives2D.create_region"><a class="viewcode-back" href="../../../API/_autosummary/pyaedt.modeler.Primitives2D.Primitives2D.create_region.html#pyaedt.modeler.Primitives2D.Primitives2D.create_region">[docs]</a>    <span class="nd">@pyaedt_function_handler</span><span class="p">()</span>
    <span class="k">def</span> <span class="nf">create_region</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">pad_percent</span><span class="o">=</span><span class="mi">300</span><span class="p">,</span> <span class="n">is_percentage</span><span class="o">=</span><span class="kc">True</span><span class="p">):</span>
        <span class="sd">&quot;&quot;&quot;Create an air region.</span>

<span class="sd">        Parameters</span>
<span class="sd">        ----------</span>
<span class="sd">        pad_percent : float, str, list of floats or list of str, optional</span>
<span class="sd">            Same padding is applied if not a list. The default is ``300``.</span>
<span class="sd">            If a list of floats or str, interpret as adding for ``[&quot;+X&quot;, &quot;+Y&quot;, &quot;-X&quot;, &quot;-Y&quot;]``.</span>
<span class="sd">        is_percentage : bool, optional</span>
<span class="sd">            Region definition in percentage or absolute value. The default is `True``.</span>

<span class="sd">        Returns</span>
<span class="sd">        -------</span>
<span class="sd">        :class:`pyaedt.modeler.Object3d.Object3d`</span>
<span class="sd">            Region object.</span>

<span class="sd">        References</span>
<span class="sd">        ----------</span>

<span class="sd">        &gt;&gt;&gt; oEditor.CreateRegion</span>
<span class="sd">        &quot;&quot;&quot;</span>
        <span class="k">if</span> <span class="ow">not</span> <span class="nb">isinstance</span><span class="p">(</span><span class="n">pad_percent</span><span class="p">,</span> <span class="nb">list</span><span class="p">):</span>
            <span class="k">if</span> <span class="bp">self</span><span class="o">.</span><span class="n">_app</span><span class="o">.</span><span class="n">xy_plane</span><span class="p">:</span>
                <span class="n">pad_percent</span> <span class="o">=</span> <span class="p">[</span><span class="n">pad_percent</span><span class="p">,</span> <span class="n">pad_percent</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="n">pad_percent</span><span class="p">,</span> <span class="n">pad_percent</span><span class="p">,</span> <span class="mi">0</span><span class="p">]</span>
            <span class="k">else</span><span class="p">:</span>
                <span class="n">pad_percent</span> <span class="o">=</span> <span class="p">[</span><span class="n">pad_percent</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="n">pad_percent</span><span class="p">,</span> <span class="n">pad_percent</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="n">pad_percent</span><span class="p">]</span>

        <span class="k">else</span><span class="p">:</span>
            <span class="k">if</span> <span class="bp">self</span><span class="o">.</span><span class="n">_app</span><span class="o">.</span><span class="n">xy_plane</span><span class="p">:</span>
                <span class="n">pad_percent</span> <span class="o">=</span> <span class="p">[</span><span class="n">pad_percent</span><span class="p">[</span><span class="mi">0</span><span class="p">],</span> <span class="n">pad_percent</span><span class="p">[</span><span class="mi">1</span><span class="p">],</span> <span class="mi">0</span><span class="p">,</span> <span class="n">pad_percent</span><span class="p">[</span><span class="mi">2</span><span class="p">],</span> <span class="n">pad_percent</span><span class="p">[</span><span class="mi">3</span><span class="p">],</span> <span class="mi">0</span><span class="p">]</span>

            <span class="k">else</span><span class="p">:</span>
                <span class="n">pad_percent</span> <span class="o">=</span> <span class="p">[</span><span class="n">pad_percent</span><span class="p">[</span><span class="mi">0</span><span class="p">],</span> <span class="mi">0</span><span class="p">,</span> <span class="n">pad_percent</span><span class="p">[</span><span class="mi">1</span><span class="p">],</span> <span class="n">pad_percent</span><span class="p">[</span><span class="mi">2</span><span class="p">],</span> <span class="mi">0</span><span class="p">,</span> <span class="n">pad_percent</span><span class="p">[</span><span class="mi">3</span><span class="p">]]</span>

        <span class="k">return</span> <span class="n">Primitives</span><span class="o">.</span><span class="n">create_region</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">pad_percent</span><span class="p">,</span> <span class="n">is_percentage</span><span class="p">)</span></div></div>
</pre></div>

              </article>
              

              
          </div>
          
      </div>
    </div>

  
  
  <!-- Scripts loaded after <body> so the DOM is not blocked -->
  <script src="../../../_static/scripts/pydata-sphinx-theme.js?digest=92025949c220c2e29695"></script>

<footer class="bd-footer"><div class="bd-footer__inner container">
  
  <div class="footer-item">
    <p class="copyright">
    &copy; Copyright (c) 2022 ANSYS, Inc. All rights reserved.<br>
</p>
  </div>
  
  <div class="footer-item">
    <p class="sphinx-version">
Created using <a href="http://sphinx-doc.org/">Sphinx</a> 5.3.0.<br>
</p>
  </div>
  
</div>
</footer>
  </body>
</html>